openapi: 3.0.0
x-bc-implicit-head: true
x-bc-implicit-options: true
x-bc-upstream: 'http://backend_server'
info:
  title: Brightcove In-Page Experiences API Reference
  description: |-
    Reference for the Brightcove In-Page Experiences API, used to access and manage your In-Page Experiences.

    **Base URL**: https://experiences.api.brightcove.com/v1
  version: 1.0.0
  x-bc-access: public
servers:
  - url: 'https://experiences.api.brightcove.com/v1'
    variables: {}
tags:
  - name: Experiences
    description: Manage your In-Page Experiences.
  - name: Interactions
    description: Manage your In-Page Experience interactions.
  - name: Templates
    description: Manage templates for In-Page Experiences.
  - name: Themes
    description: Manage themes for In-Page Experiences.
  - name: Fonts
    description: Manage fonts for In-Page Experiences.
paths:
  '/accounts/{account_id}/experiences':
    get:
      summary: Get In-Page Experiences
      description: Gets a list of all experiences in the account
      operationId: GetExperiences
      tags:
        - Experiences
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/experience/read
    post:
      summary: Create In-Page Experience
      description: Creates an In-Page Experience
      operationId: CreateExperience
      tags:
        - Experiences
      security:
        - BC_OAuth2:
            - video-cloud/experience/all
  '/accounts/{account_id}/experiences/{experience_id}':
    get:
      summary: Get In-Page Experience
      description: Gets a specific In-Page Experience in the account
      operationId: GetExperience
      tags:
        - Experiences
      security:
        - BC_OAuth2:
            - video-cloud/experience/read
    put:
      summary: Update In-Page Experience
      description: Updates an In-Page Experience
      operationId: UpdateExperience
      tags:
        - Experiences
      security:
        - BC_OAuth2:
            - video-cloud/experience/all
    delete:
      summary: Delete In-Page Experience
      description: Deletes an In-Page Experience
      operationId: DeleteExperience
      tags:
        - Experiences
      security:
        - BC_OAuth2:
            - video-cloud/experience/all
  '/accounts/{account_id}/experiences/{experience_id}/actions/publish':
    post:
      summary: Publish In-Page Experience
      description: >-
        Publish the specified In-Page Experience. This will initiate a publish,
        you can poll the GET endpoint for fetching the In-Page Experience to
        check its published status to see when publishing completes
      operationId: PublishExperience
      tags:
        - Experiences
      security:
        - BC_OAuth2:
            - video-cloud/experience/all
  '/accounts/{account_id}/experiences/{experience_id}/actions/unpublish':
    post:
      summary: Unpublish In-Page Experience
      description: >-
        Takes the specified In-Page Experience offline. If this In-Page
        Experience is embedded anywhere, it will be replaced with text notifying
        the end user that it is offline. This will initiate an unpublish, you
        can poll the GET endpoint for fetching the In-Page Experience to check
        its published status to see when unpublishing completes
      operationId: UnpublishExperience
      tags:
        - Experiences
      security:
        - BC_OAuth2:
            - video-cloud/experience/all
  '/accounts/{account_id}/experiences/{experience_id}/actions/duplicate':
    post:
      summary: Duplicate In-Page Experience
      description: >-
        Duplicates the specified In-Page Experience and all of its associated
        interactivity
      operationId: DuplicateExperience
      tags:
        - Experiences
      security:
        - BC_OAuth2:
            - video-cloud/experience/all
  '/accounts/{account_id}/experiences/{experience_id}/live/status':
    get:
      summary: Get In-Page Experience Live Status
      description: Gets the live event status of the specified In-Page Experience
      operationId: GetExperienceLiveStatus
      tags:
        - Experiences
      security:
        - BC_OAuth2:
            - video-cloud/experience/read
    put:
      summary: Set In-Page Experience Live Status
      description: Sets the live event status of the specified In-Page Experience
      operationId: SetExperienceLiveStatus
      tags:
        - Experiences
      security:
        - BC_OAuth2:
            - video-cloud/experience/all
  '/accounts/{account_id}/interactions':
    get:
      summary: Get In-Page Experience Interactions
      description: Retrieves a list of interactions related to the given accountId.
      operationId: GetInteractions
      tags:
        - Interactions
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/experience/read
    post:
      summary: Create In-Page Experience Interaction
      description: Creates an In-Page Experience Interaction
      operationId: CreateInteraction
      tags:
        - Interactions
      security:
        - BC_OAuth2:
            - video-cloud/experience/all
  '/accounts/{account_id}/interactions/{interaction_id}':
    get:
      summary: Get In-Page Experience Interaction
      description: Gets a specific In-Page Experience interaction in the account
      operationId: GetInteraction
      tags:
        - Interactions
      security:
        - BC_OAuth2:
            - video-cloud/experience/read
    put:
      summary: Update an interaction
      description: Updates an interaction
      operationId: UpdateInteraction
      tags:
        - Interactions
      security:
        - BC_OAuth2:
            - video-cloud/experience/all
    delete:
      summary: Delete an interaction
      description: Deletes an interaction
      operationId: DeleteInteraction
      tags:
        - Interactions
      security:
        - BC_OAuth2:
            - video-cloud/experience/all
  '/accounts/{account_id}/templates':
    get:
      summary: Get Templates
      description: Gets all templates available to the account
      operationId: GetTemplates
      tags:
        - Templates
      security:
        - BC_OAuth2:
            - video-cloud/experience/read
  '/accounts/{account_id}/templates/{template_id}':
    get:
      summary: Get Template
      description: Gets the specified template
      operationId: GetTemplate
      tags:
        - Templates
      security:
        - BC_OAuth2:
            - video-cloud/experience/read
  '/accounts/{account_id}/themes':
    get:
      summary: Get Themes
      description: Gets all themes for the account
      operationId: GetThemes
      tags:
        - Themes
      security:
        - BC_OAuth2:
            - video-cloud/experience/read
    post:
      summary: Create Theme
      description: Creates a new theme
      operationId: CreateTheme
      tags:
        - Themes
      security:
        - BC_OAuth2:
            - video-cloud/experience/all
  '/accounts/{account_id}/themes/{theme_id}':
    get:
      summary: Get Theme
      description: Gets the specified theme
      operationId: GetTheme
      tags:
        - Themes
      security:
        - BC_OAuth2:
            - video-cloud/experience/read
    put:
      summary: Update Theme
      description: Updates the specified theme
      operationId: UpdateTheme
      tags:
        - Themes
      security:
        - BC_OAuth2:
            - video-cloud/experience/all
    delete:
      summary: Delete Theme
      description: Deletes the specified theme
      operationId: DeleteTheme
      tags:
        - Themes
      security:
        - BC_OAuth2:
            - video-cloud/experience/all
  '/accounts/{account_id}/fonts':
    get:
      summary: Get Fonts
      description: Gets all fonts for the account
      operationId: GetFonts
      tags:
        - Fonts
      security:
        - BC_OAuth2:
            - video-cloud/experience/read
    post:
      summary: Create Font
      description: Creates a font
      operationId: CreateFont
      tags:
        - Fonts
      security:
        - BC_OAuth2:
            - video-cloud/experience/all
  '/accounts/{account_id}/fonts/{font_id}':
    get:
      summary: Get Font
      description: Gets the specified font
      operationId: GetFont
      tags:
        - Fonts
      security:
        - BC_OAuth2:
            - video-cloud/experience/read
    put:
      summary: Update Font
      description: Updates the specified font
      operationId: UpdateFont
      tags:
        - Fonts
      security:
        - BC_OAuth2:
            - video-cloud/experience/all
    delete:
      summary: Delete Font
      description: Deletes the specified font
      operationId: DeleteFont
      tags:
        - Fonts
      security:
        - BC_OAuth2:
            - video-cloud/experience/all
components:
  securitySchemes:
    BC_OAuth2:
      type: oauth2
      description: >-
        Brightcove OAuth API. See the [support
        documentation](https://apis.support.brightcove.com/oauth/) or [Getting
        Access
        Tokens](https://apis.support.brightcove.com/oauth/guides/getting-access-tokens.html
        to learn more
      flows:
        clientCredentials:
          tokenUrl: 'https://oauth.brightcove.com/v4/access_token'
          scopes:
            video-cloud/experience/read: Read
            video-cloud/experience/all: All
